"use strict";

/** Domain event type constants — single source of truth. */
module.exports = {
  PLAYER_REGISTERED: "PLAYER_REGISTERED",
  REFERRAL_LINKED: "REFERRAL_LINKED",
  PLAYER_GAINED_XP: "PLAYER_GAINED_XP",
  PLAYER_LEVEL_UP: "PLAYER_LEVEL_UP",
  PLAYER_DEPOSIT_COMPLETED: "PLAYER_DEPOSIT_COMPLETED",
  PLAYER_COMPLETED_GAME: "PLAYER_COMPLETED_GAME",
  PLAYER_COMPLETED_SPIN: "PLAYER_COMPLETED_SPIN",
  INVITEE_QUALIFIED: "INVITEE_QUALIFIED",
  REFERRAL_MILESTONE_READY: "REFERRAL_MILESTONE_READY",
  REFERRAL_MILESTONE_COMPLETED: "REFERRAL_MILESTONE_COMPLETED",
  FRAUD_RISK_UPDATED: "FRAUD_RISK_UPDATED",
  REFERRAL_REWARD_CLAIM_REQUESTED: "REFERRAL_REWARD_CLAIM_REQUESTED",
  PLAYER_SESSION_STARTED: "PLAYER_SESSION_STARTED",
};
